baseURL: "https://baudelairefox.github.io/" 
title: Fox Baudelaire
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: foxbaudelaire

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Aperçus
          url: /apercus/
          weight: 2
        - name: Articles and Letters
          url: /articles-and-letters/
          weight: 3
        - name: Featured Profile
          url: https://alumni.brandeis.edu/stories/students/scholars/baudelaire-fox.html
          weight: 4     
        - name: Tags
          url: /tags/
          weight: 5

params:
    description: "I am an interdisciplinary scientist, scholar, and Renaissance man ever in the making. Through an award from the Fulbright U.S. Student Program, I am currently a visiting researcher in the Department of Physics at Toronto Metropolitan University in Canada. My primary research interests span theory and computation from modern thermodynamics and statistical mechanics applied to problems at the chemistry-biology interface. Other interests of mine are in education, philosophy, and social justice. Now aspiring to a doctorate, I have graduated from the University of Michigan, Brandeis University, and Bunker Hill Community College. "
    author: Fox Baudelaire
    # googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Fox Baudelaire
          subtitle: "I am an interdisciplinary scientist, scholar, and Renaissance man ever in the making. Through an award from the Fulbright U.S. Student Program, I am currently a visiting researcher in the Department of Physics at Toronto Metropolitan University in Canada. My primary research interests span theory and computation from modern thermodynamics and statistical mechanics applied to problems at the chemistry-biology interface. With further interests in education, philosophy, and social justice, my activities also touch on such themes as human-centered STEM instruction, bridging the two-cultures divide, and liberatory access to participation in science beyond contemporary DEI (diversity, equity, inclusion) frameworks."
          imageUrl: "/fblaire_profile_Apr2024-r1.png"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Fox Baudelaire
          buttons:
            - name: Papers
              url: /papers/
            - name: Aperçus
              url: /apercus/
            - name: Articles and Letters
              url: /articles-and-letters/
            - name: Newsletter
              url: https://foxbaudelaire.substack.com
            - name: Featured Profile
              url: https://alumni.brandeis.edu/stories/students/scholars/baudelaire-fox.html
    socialIcons:
        - name: CV
          url: /FoxBaudelaireCV_Oct2023-public.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=te0XsfwAAAAJ
        - name: LinkedIn
          url: https://www.linkedin.com/in/baudelairefox/
        - name: Twitter
          url: https://twitter.com/foxbaudelaire
        - name: GitHub
          url: https://github.com/baudelairefox?tab=repositories
        - name: ORCiD
          url: https://orcid.org/0000-0002-5551-6851        
        # - name: YouTube
        #  url: https://www.youtube.com/
        # - name: Email
        #  url: mailto:fblaire@umich.edu
        # - name: Location
        #   url: /location/
        # - name: Office Hours
        #  url: /officehours/
        # - name: Substack
        #   url: https://foxbaudelaire.substack.com
        # - name: Ko-fi
        #   url: https://kofi.com

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Fox Baudelaire"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
